sources:
  - name: graph-network-mainnet
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/graphprotocol/graph-network-mainnet

documents:
  - "./queries/**/*.graphql"
  # - "./mutations/**/*.graphql"
